### PR TITLE
Support for Condition on script elements plus ability to run on uninstall

### PR DESCRIPTION
**Pull request by flcdrg**
This PR combines the changes made by @nirbar to introduce conditions to the script blocks plus it also provides the ability to have scripts run during uninstall of the package.

Based on #22 and #25 

Thanks to @GZidar for updates in #25

### CODE REVIEW

**Comment by flcdrg** [comment]
@nirbar and @GZidar thanks for all your work on the commits.

I ended up spending a bit of time switching to GitHub Actions for CI/CD builds, automate release notes and add a test run to smoke test some of the tests.

I've published a new version as a pre-release. If you can give it a try and let me know if it's all behaving as expected. Once I hear back that it's good, I'll do a non-pre-release version.

**Comment by GZidar** [comment]
I have used the latest version of the dll after deleting my fork and repointing back to your library, and so far things seem to be working as expected. I will let you know if I notice anything out of the ordinary.

**Comment by flcdrg** [comment]
Thanks!

**Comment by smariano88** [comment]
Any doc on how to use these changes?

**Comment by nirbar** [comment]
@smariano88 Visual Studio InteliSense doesn that with the XSD file (auto-complete)

**Pull request merged**
