### PR TITLE
Support 'Condition' on scripts and files

### PR DESCRIPTION
**Pull request by nirbar**
Let the author set a condition to execute each script and file.

### CODE REVIEW

**Comment by flcdrg** [comment]
Apologies for not following this up earlier.

A question about the change to AnyCPU from x86 - have you tested this against WiX projects that target x86 and separately x64 to confirm that the assemblies load correctly?

**Comment by nirbar** [comment]
@flcdrg It has been a while since I made the changes so I don't quite remember

**Comment by GZidar** [comment]
Is there any chance that this might get merged into the main repository? I was about to start making the same kinds of changes but if this were likely to get merged soon I will wait.

**Comment by flcdrg** [comment]
@GZidar is there any chance you could test it out (as per my question above). If someone can confirm it behaves correctly then I'm happy to merge it in.

**Comment by flcdrg** [comment]
I think that would remove my uncertainty about the impact, yes.

**Comment by flcdrg** [comment]
Superceded by #32

**Pull request closed without merging**
